### ISSUE TITLE
euca-deploy prepare can fail on first run

### ISSUE THREAD

**Issue by tbeckham** [viglesiasce/euca-deploy#13]
I have seen prepare fail consistently for a set of hosts I deploy to. I notice it after a fresh pxe of each host and starting from scratch with euca-deploy according to the README. When it comes to the first deploy step, "euca-deploy prepare", the execution fails with "Unable to find node" error for the hosts involved. Unfortunately I did not grab other logs but I do have the output of the symptom.  A workaround is to rerun the command. 

> [root@c-06 euca-deploy]# euca-deploy prepare -p foobar
> Creating Chef repository
> Initialized empty Git repository in /root/euca-deploy/eucalyptus-cookbook/.git/
> remote: Counting objects: 3222, done.
> remote: Compressing objects: 100% (934/934), done.
> remote: Total 3222 (delta 2151), reused 3209 (delta 2143)
> Receiving objects: 100% (3222/3222), 586.45 KiB, done.
> Resolving deltas: 100% (2151/2151), done.
> Branch testing set up to track remote branch testing from origin.
> Switched to a new branch 'testing'
> Downloading Chef cookbooks
> Syncing SSH keys with system under deployment
> Unable to find node:10.111.1.41
> Unable to find node:10.111.1.41
> Unable to find node:10.111.1.41
> Unable to find node:10.111.1.135
> Unable to find node:10.111.1.135
> Unable to find node:10.111.5.101
> Unable to find node:10.111.5.151
> Unable to find node:10.111.1.61
> Unable to find node:10.111.1.61
> Unable to find node:10.111.1.175
> Unable to find node:10.111.5.88

**Comment by viglesiasce** [comment]
I believe this should be fixed with the changes from last night.
